const express =require('express')
const mongoose=require('mongoose')
const dotenv=require('dotenv')
dotenv.config()
mongoose.connect(process.env.DATABASA_ACCESS,()=>console.log('Database Connected Successfully'))
const app= express()
app.listen(4000,()=>console.log('Server is up and running'))